jobs:
- job: 'CodeBuild'
  pool:
    name: DAS - Continuous Integration Agents
    demands: LATEST_DOTNET_VERSION -equals 3.1
  workspace:
    clean: all

  steps:
  - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks

  - template: azure-pipelines-templates/build/step/app-build.yml@das-platform-building-blocks
    parameters:
        SonarCloudProjectKey: SkillsFundingAgency_das-pensionsregulator

  - task: DotNetCoreCLI@2
    displayName: 'Publish Internal API'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/PensionsRegulatorApi/PensionsRegulatorApi.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore  --no-build'

  - task: DotNetCoreCLI@2
    displayName: 'Publish Internal API'
    inputs:
      command: publish
      publishWebProjects: false
      projects: 'src/PensionsRegulatorApi/PensionsRegulatorApi.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore  --no-build'

  - task: ArchiveFiles@2
    displayName: 'Package DataSync Function'
    inputs:
      rootFolderOrFile: 'src/SFA.DAS.PensionsRegulator.DataSync'
      includeRootFolder: false
      archiveFile: "$(build.artifactstagingdirectory)/publish/SFA.DAS.PensionsRegulator.DataSync.zip"

  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      Contents: |
        azure/**
        src/**/*.publish.xml
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)/publish'
