DECLARE @Date Date

SET @Date=getdate()

IF @Date < '2019-10-20'
BEGIN

IF  EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'CI_TPR_UniqueKey') 
DROP INDEX [CI_TPR_UniqueKey] ON dbo.Stg_Tpr_1218



IF  EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'NCI_TPR_AORN') 
DROP INDEX [NCI_TPR_AORN] ON dbo.Stg_Tpr_1218



IF  EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'NCI_TPR_PAYE') 
DROP INDEX [NCI_TPR_PAYE] ON dbo.Stg_Tpr_1218



IF  EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'NCI_TPR_PAYE_AORN') 
DROP INDEX [NCI_TPR_PAYE_AORN] ON dbo.Stg_Tpr_1218



IF  EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'[NCI_TPR_PAYE_DERIVED') 
DROP INDEX [NCI_TPR_PAYE_DERIVED] ON dbo.Stg_Tpr_1218

END