
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'CI_TPR_UniqueKey' AND object_id = OBJECT_ID('Stg_Tpr_1218')) 
CREATE CLUSTERED INDEX [CI_TPR_UniqueKey] ON [dbo].[Stg_Tpr_1218]([UniqueID])



IF NOT EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'NCI_TPR_AORN' AND object_id = OBJECT_ID('Stg_Tpr_1218')) 
CREATE NONCLUSTERED INDEX [NCI_TPR_AORN] ON [dbo].[Stg_Tpr_1218]([AORN])



IF NOT EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'NCI_TPR_PAYE' AND object_id = OBJECT_ID('Stg_Tpr_1218')) 
CREATE NONCLUSTERED INDEX [NCI_TPR_PAYE] ON [dbo].[Stg_Tpr_1218]([PAYESchemeRef])


IF NOT  EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'NCI_TPR_PAYE_AORN' AND object_id = OBJECT_ID('Stg_Tpr_1218')) 
CREATE NONCLUSTERED INDEX [NCI_TPR_PAYE_AORN] ON [dbo].[Stg_Tpr_1218]([PAYESchemeRef],[AORN])



IF NOT  EXISTS (SELECT * FROM sys.indexes WHERE NAME = N'NCI_TPR_PAYE_DERIVED' AND object_id = OBJECT_ID('Stg_Tpr_1218')) 
CREATE NONCLUSTERED INDEX [NCI_TPR_PAYE_DERIVED] ON [dbo].[Stg_Tpr_1218](PayeDerived)


